language: python
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev python-gevent python-m2crypto
  - pip install gevent
script:
  - python test.py
